# Generated by Django 4.2.1 on 2023-05-06 09:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("todoapp", "0001_initial"),
    ]

    operations = [
        migrations.AlterField(
            model_name="todo",
            name="description",
            field=models.TextField(blank=True, max_length=250, null=True),
        ),
    ]
